"""Alembic migrations for core-api.

## What checks this directory, and what does not

**ruff and pyright DO.** `pyproject.toml` names `migrations` in pyright's
`include`, added 2026-08-05 after review found the directory had never been type
checked at all: `include` was `["src", "tests"]`, and three real errors were
sitting in `0001` — two false return annotations (`Column` is invariant, so
`Column[UUID]` is not a `Column[object]`) and one `Column[Unknown]`. They had
been written to a checker that was never going to look at them. If you add a
revision, `uv run pyright` covers it.

**🔴 `scripts/check_backend_rules.py` DOES NOT, AND NOTHING REPLACES IT HERE.**
The gate's scan roots are `services/*/src` and `libs/*/src`;
`services/core-api/migrations/` is under neither, and the scanned-file count
does not move when a revision is added. *Verified 2026-08-05: a migration
carrying a `print(`, an `Any` and a bare `text(...)` reported clean.* That
default is defensible — a migration is mostly raw SQL by nature, which is what
the `db/` carve-out exists for — but it means **the structural rules here are
held by review and by pyright, not by the gate**. Stated here so nobody reads
the gate's silence as approval.

🔴 AND IT HAS NO OWNER. This paragraph used to end "Widening the scan roots
touches `scripts/` and belongs to Task 7." Task 7 landed — it is CI, commits
`3a5a652` and `9ddeefc` — and it did not widen them. `SCAN_ROOT_GLOBS` is still
`("services/*/src", "libs/*/src")` and has not been edited since the commit that
introduced it (`160fcff`). Nor was it ever Task 7's: Plan 01's Task 4 section
asks for "either widen the scan roots … or state in the migration package's
`__init__.py` that it is deliberately outside the gate", and this docstring IS
the second branch. The requirement is met and the widening has no owner — which
is a different thing from work that is queued, and a forward reference to a task
that has already shipped reads as the second while being the first.

The rules the gate would have applied still hold here, and the two that matter
most in a migration are:

* **no `print`** — the migration's output channel is Alembic's logger;
* **no `Any` / `cast(`** — a migration that needs either has usually
  autogenerated something nobody read.

Raw SQL, by contrast, is the medium. `op.execute` is how a trigger, a policy or
a grant reaches the database at all, because SQLAlchemy metadata cannot express
any of the three.

## The two rules that are not stylistic

**Revision ids are hand-written decimal strings** — `"0001"`, `"0002"`, … — not
hashes. Task 4's `down_revision = "0001"` has to be readable by the person
writing it. `alembic.ini` sets `file_template` so the file name carries the id.

**A migration is a frozen snapshot and must not import from
`titlepipe_core`.** `0001` repeats the `na_reason` labels rather than importing
`NA_REASON_LABELS`, so that editing the model cannot retroactively change what
`0001` claims to have created. `tests/test_schema_migration.py` asserts the live
catalog against the model's constant, which is what keeps the copy honest
without coupling the snapshot to it.

**Hand-write migrations.** `--autogenerate` cannot see policies, grants, roles,
triggers or the enum's `DROP TYPE`. It is useful as a second opinion; it is not
the author.
"""

__all__: list[str] = []
