import { Field } from "@titlepipe/contract";

export const MOCK_SCREENSHOT_FIELDS: Field[] = [
  {
    id: "fld_vesting_inst",
    order_id: "ord_1",
    path: "deed.instrument_number",
    value: "2019-0161820",
    state: "needs_review",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 4,
    source_snippet: "",
    source_line_coords: [[0.2, 0.15, 0.6, 0.20]],
    engine_id: "llm",
    engine_confidence_raw: 0.5,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
    asking: "",
    why: "Low confidence — O/O ambiguity in the recording stamp · Send back to search"
  },
  {
    id: "fld_vesting_type",
    order_id: "ord_1",
    path: "deed.deed_type",
    value: "Administrator's Deed",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 4,
    source_snippet: "",
    source_line_coords: [[0.2, 0.27, 0.6, 0.32]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },
  {
    id: "fld_vesting_grantor",
    order_id: "ord_1",
    path: "deed.grantor",
    value: "Estate of Ruby M. Aldridge",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 4,
    source_snippet: "",
    source_line_coords: [[0.2, 0.31, 0.6, 0.36]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },
  {
    id: "fld_vesting_grantee",
    order_id: "ord_1",
    path: "deed.grantee",
    value: "Marcus T. Whitfield",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 4,
    source_snippet: "",
    source_line_coords: [[0.2, 0.39, 0.6, 0.44]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },
  {
    id: "fld_vesting_recorded",
    order_id: "ord_1",
    path: "deed.recorded",
    value: "08/22/2016",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 4,
    source_snippet: "",
    source_line_coords: [[0.2, 0.19, 0.6, 0.24]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },
  {
    id: "fld_vesting_book",
    order_id: "ord_1",
    path: "deed.book_page",
    value: "59917/242",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 4,
    source_snippet: "",
    source_line_coords: [[0.2, 0.15, 0.6, 0.20]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },

  {
    id: "fld_sec_min",
    order_id: "ord_1",
    path: "mortgages.1.min",
    value: "1000312-0004567891-2",
    state: "needs_review",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 9,
    source_snippet: "",
    source_line_coords: [[0.2, 0.35, 0.6, 0.40]],
    engine_id: "llm",
    engine_confidence_raw: 0.5,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
    why: "Checksum digit unreadable on scan · Send back to search"
  },
  {
    id: "fld_sec_lender",
    order_id: "ord_1",
    path: "mortgages.1.lender",
    value: "Pinnacle Bank",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 9,
    source_snippet: "",
    source_line_coords: [[0.2, 0.27, 0.6, 0.32]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },
  {
    id: "fld_sec_amt",
    order_id: "ord_1",
    path: "mortgages.1.amount",
    value: "$284,000.00",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 10,
    source_snippet: "",
    source_line_coords: [[0.2, 0.20, 0.6, 0.25]],
    engine_id: "llm",
    engine_confidence_raw: 0.99,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },
  {
    id: "fld_sec_rec",
    order_id: "ord_1",
    path: "mortgages.1.recorded",
    value: "08/22/2016",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 9,
    source_snippet: "",
    source_line_coords: [[0.2, 0.15, 0.6, 0.20]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },

  {
    id: "fld_ass_rec",
    order_id: "ord_1",
    path: "assignment.1.recorded",
    value: null,
    state: "needs_review",
    na_reason: "NOT_PRESENT",
    source_doc_id: "doc_1",
    source_page: 17,
    source_snippet: "",
    source_line_coords: [[0.2, 0.15, 0.6, 0.20]],
    engine_id: "llm",
    engine_confidence_raw: 0.5,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
    why: "Recording stamp not found on pg 17 — blocking validator · Send back to search"
  },
  {
    id: "fld_ass_assignor",
    order_id: "ord_1",
    path: "assignment.1.assignor",
    value: "MERS, as nominee",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 17,
    source_snippet: "",
    source_line_coords: [[0.2, 0.20, 0.6, 0.25]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },
  {
    id: "fld_ass_assignee",
    order_id: "ord_1",
    path: "assignment.1.assignee",
    value: "Lakeview Loan Servicing, LLC",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 17,
    source_snippet: "",
    source_line_coords: [[0.2, 0.25, 0.6, 0.30]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },

  {
    id: "fld_judg_amt",
    order_id: "ord_1",
    path: "judgments.1.amount",
    value: "$12,449.18",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 24,
    source_snippet: "",
    source_line_coords: [[0.2, 0.45, 0.6, 0.50]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },
  {
    id: "fld_judg_filed",
    order_id: "ord_1",
    path: "judgments.1.filed",
    value: "02/09/2026",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 24,
    source_snippet: "",
    source_line_coords: [[0.2, 0.50, 0.6, 0.55]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  },

  {
    id: "fld_tax_city",
    order_id: "ord_1",
    path: "assessment.city_tax",
    value: "Not Available",
    state: "needs_review",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 31,
    source_snippet: "",
    source_line_coords: [[0.2, 0.45, 0.6, 0.50]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
    why: "No city tax printout in package · Send back to search"
  },
  {
    id: "fld_tax_county",
    order_id: "ord_1",
    path: "assessment.county_tax_2025",
    value: "$1,433.00",
    state: "confirmed",
    na_reason: null,
    source_doc_id: "doc_1",
    source_page: 31,
    source_snippet: "",
    source_line_coords: [[0.2, 0.55, 0.6, 0.60]],
    engine_id: "llm",
    engine_confidence_raw: 0.9,
    rule_refs: [],
    approved_by: null,
    approved_at: null,
  }
];
