"""Migration `0001`, read back from the live catalog rather than from the file.

The database is an EPHEMERAL CONTAINER — see `conftest.py`'s database seam. The
migration is applied by the module-scoped `migrated_database` fixture, which
also puts the database back exactly as it found it; that teardown is not
housekeeping, and its docstring says what breaks without it.

Nothing here is skipped. If Docker or `psql` is unavailable these tests FAIL.

THE CONTAINMENT LESSON FROM TASK 2 APPLIES TO EVERY ENUMERATION BELOW. Five
decoy roles satisfied a `>= 5` cardinality floor while two real roles were
missing, and a table enumeration is satisfied by the wrong seven tables just as
readily as by the right ones. So each enumeration asserts an EXACT SET — of
table names, of column names per table, of enum labels in order, of trigger
names — never a count and never a subset.
"""

from __future__ import annotations

import os
from collections.abc import Callable
from pathlib import Path
from typing import NamedTuple

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Connection, create_engine, text
from sqlalchemy.exc import DBAPIError, OperationalError

from titlepipe_core.db.models import NA_REASON_LABELS, Base

# The exact seven. `alembic_version` is asserted alongside them rather than
# filtered out: it is created outside every revision script, it is the one table
# nobody writes a `CREATE TABLE` for, and Task 2 cared specifically that it lands
# on the owner like everything else.
SKELETON_TABLES = frozenset(
    {"tenants", "orders", "packages", "pages", "fields", "field_readings", "audit_log"}
)

# Every skeleton table has these two.
IDENTITY_COLUMNS = frozenset({"id", "created_at"})

# 🔴 `tenants` HAS NO `tenant_id` AND THAT IS THE CONTRACT, not an omission. It
# is the registry: its primary key *is* the tenant id, so Task 4's policy keys on
# `id` there. Task 4 derives which tables are tenant tables from the presence of
# this column, so an extra one here would silently give the registry the wrong
# policy.
EXPECTED_COLUMNS: dict[str, frozenset[str]] = {
    "tenants": IDENTITY_COLUMNS,
    "orders": IDENTITY_COLUMNS | {"tenant_id"},
    "packages": IDENTITY_COLUMNS | {"tenant_id"},
    "pages": IDENTITY_COLUMNS | {"tenant_id"},
    "fields": IDENTITY_COLUMNS | {"tenant_id", "na_reason"},
    "field_readings": IDENTITY_COLUMNS | {"tenant_id", "line_coords"},
    "audit_log": IDENTITY_COLUMNS | {"tenant_id"},
}

EXPECTED_TRIGGERS = frozenset({"audit_log_append_only", "audit_log_no_truncate"})

# `pg_trigger.tgenabled` for an ordinary, firing trigger. The other three values
# — `'D'` disabled, `'R'` replica, `'A'` always — all change when the trigger
# fires, and `'D'` means never.
TRIGGER_ENABLED = "O"

# The two server defaults every skeleton table carries, as PostgreSQL renders
# them back. Read from the catalog rather than assumed: `tenants` is seeded by
# Task 6, which supplies no `id`, so its default is the only thing producing one.
UUID_DEFAULT = "gen_random_uuid()"
NOW_DEFAULT = "now()"

# `feature_not_supported`, raised by the trigger. Asserted instead of "something
# raised", because a typo'd column raises too — as `42703`, and a typo'd table as
# `42P01`. Neither can be mistaken for this one.
APPEND_ONLY_SQLSTATE = "0A000"

FIRST_REVISION = "0001"

# `migrations/env.py`'s three DSN sources, in the order it consults them.
DATABASE_URL_VARIABLE = "TITLEPIPE_DATABASE_URL"
ALEMBIC_DSN_ATTRIBUTE = "dsn"

# A DSN that resolves and refuses fast. Port 1 on loopback is not listening, so
# every precedence test below fails in milliseconds when the WRONG source wins,
# and never reaches a real server.
UNREACHABLE_DSN = "postgresql+psycopg://nobody:nobody@127.0.0.1:1/nowhere"


def _tables(connection: Connection) -> set[str]:
    """Ordinary tables in `public`. Views, sequences and indexes are not tables."""
    result = connection.execute(
        text(
            "SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE n.nspname = 'public' AND c.relkind = 'r'"
        )
    )
    return {str(row[0]) for row in result}


def _table_owners(connection: Connection) -> dict[str, tuple[str, bool]]:
    """table -> (owner role, whether that role can log in).

    `pg_roles` rather than `pg_authid` for `rolcanlogin`: the view carries it and
    is readable without a superuser, so this assertion does not depend on which
    DSN it is handed.
    """
    result = connection.execute(
        text(
            "SELECT c.relname, r.rolname, r.rolcanlogin "
            "FROM pg_class c "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            "JOIN pg_roles r ON r.oid = c.relowner "
            "WHERE n.nspname = 'public' AND c.relkind = 'r'"
        )
    )
    return {str(row[0]): (str(row[1]), bool(row[2])) for row in result}


class ColumnFacts(NamedTuple):
    """Type, nullability and server default — the three things a skeleton column is.

    `default` was not read at all until review pointed it out, so six of seven
    tables' defaults were unverified. It is not decoration: Task 6 seeds
    `tenants` without supplying an `id`, so `gen_random_uuid()` is the only thing
    producing one, and a migration that dropped the default would surface there
    as a `NOT NULL` violation in somebody else's task.
    """

    type_name: str
    nullable: bool
    default: str | None


def _columns(connection: Connection) -> dict[str, dict[str, ColumnFacts]]:
    """table -> column -> `ColumnFacts`.

    `udt_name` rather than `data_type`: `data_type` reports `USER-DEFINED` for an
    enum and `ARRAY` for anything array-shaped, so it cannot tell `na_reason`
    from any other user-defined type.
    """
    result = connection.execute(
        text(
            "SELECT table_name, column_name, udt_name, is_nullable, column_default "
            "FROM information_schema.columns WHERE table_schema = 'public'"
        )
    )
    columns: dict[str, dict[str, ColumnFacts]] = {}
    for row in result:
        columns.setdefault(str(row[0]), {})[str(row[1])] = ColumnFacts(
            str(row[2]), str(row[3]) == "YES", None if row[4] is None else str(row[4])
        )
    return columns


def _public_schema_objects(connection: Connection) -> dict[str, set[str]]:
    """Everything in `public` that a migration could have created and left behind.

    Broader than the table set on purpose. The round trip used to diff tables and
    `pg_enum` only, so a downgrade that leaked a FUNCTION, a SEQUENCE, a VIEW or
    a standalone INDEX was invisible to it — and `0001` creates a function, which
    is exactly one of the blind spots.

    Indexes belonging to `alembic_version` are excluded: that table survives
    `downgrade base` by design, so its primary-key index does too, and its name
    is Alembic's to choose rather than ours to hardcode.
    """
    relations = connection.execute(
        text(
            "SELECT c.relkind, c.relname FROM pg_class c "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE n.nspname = 'public' AND c.relkind IN ('r', 'S', 'v', 'm', 'p', 'f')"
        )
    )
    indexes = connection.execute(
        text(
            "SELECT indexname FROM pg_indexes "
            "WHERE schemaname = 'public' AND tablename <> :version_table"
        ),
        {"version_table": "alembic_version"},
    )
    functions = connection.execute(
        text(
            "SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace "
            "WHERE n.nspname = 'public'"
        )
    )
    enum_types = connection.execute(
        text(
            "SELECT t.typname FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace "
            "WHERE n.nspname = 'public' AND t.typtype = 'e'"
        )
    )
    return {
        "relations": {f"{row[0]}:{row[1]}" for row in relations},
        "indexes": {str(row[0]) for row in indexes},
        "functions": {str(row[0]) for row in functions},
        "enum_types": {str(row[0]) for row in enum_types},
    }


def _enum_labels(connection: Connection, type_name: str) -> tuple[str, ...]:
    """The type's labels in `enumsortorder`, or `()` when the type does not exist.

    `ORDER BY e.enumsortorder` is the server's own ordering, which is what a
    comparison, a `<` and a `MIN()` over the type would use. Reading the rows
    unordered and sorting them here would make the order assertion vacuous.
    """
    result = connection.execute(
        text(
            "SELECT e.enumlabel FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid "
            "WHERE t.typname = :type_name ORDER BY e.enumsortorder"
        ),
        {"type_name": type_name},
    )
    return tuple(str(row[0]) for row in result)


class TriggerFacts(NamedTuple):
    """What has to be true of an append-only trigger for it to be one.

    All three, because each can be broken without touching the others, and
    breaking any one of them switches the protection off:

    * `is_statement_level` — `tgtype & 1` is `TRIGGER_TYPE_ROW`. A row trigger
      does not fire when a statement matches nothing, which is exactly the case
      under Task 4's RLS;
    * `is_before` — `tgtype & 2` is `TRIGGER_TYPE_BEFORE`. `0001` calls this
      load-bearing ("so nothing is written before the refusal") and until now
      nothing asserted it;
    * `enabled` — `tgenabled`, which was NOT being read at all. MEASURED
      2026-08-05: `titlepipe_migration` with `SET ROLE titlepipe_owner` can issue
      `ALTER TABLE audit_log DISABLE TRIGGER ALL`, after which `tgenabled` is
      `'D'` and **`tgtype` is unchanged** — so a check on `tgtype` alone passes
      with the trigger switched off. `'O'` is "fires in origin/local
      replication role", which is the ordinary enabled state.
    """

    is_statement_level: bool
    is_before: bool
    enabled: str


def _triggers(connection: Connection, table: str) -> dict[str, TriggerFacts]:
    """trigger name -> the three facts above.

    `tgisinternal` triggers are the ones PostgreSQL creates for constraints; they
    are not ours and would make an exact-set assertion impossible to write.
    """
    result = connection.execute(
        text(
            "SELECT t.tgname, (t.tgtype & 1) = 0, (t.tgtype & 2) <> 0, t.tgenabled "
            "FROM pg_trigger t "
            "JOIN pg_class c ON c.oid = t.tgrelid "
            "WHERE c.relname = :table AND NOT t.tgisinternal"
        ),
        {"table": table},
    )
    return {str(row[0]): TriggerFacts(bool(row[1]), bool(row[2]), str(row[3])) for row in result}


def _sqlstate(error: DBAPIError) -> str | None:
    """The five-character SQLSTATE psycopg attached, if it attached one.

    Checked with `isinstance` rather than trusted: `getattr` on a DBAPI exception
    returns whatever is there, and a test that compared `Any` to a string would
    pass for a `None` as readily as for a code.
    """
    sqlstate = getattr(error.orig, "sqlstate", None)
    return sqlstate if isinstance(sqlstate, str) else None


def test_the_first_revision_id_is_the_literal_0001(alembic_config: Callable[[str], Config]) -> None:
    """Task 4's `0002` sets `down_revision = "0001"`, so the id is a contract.

    Alembic's default is a random hash. A hash would work exactly as well for
    Alembic and not at all for the person writing `0002`, who would have to look
    it up and would have nothing to notice if they looked up the wrong one.

    🔴 THIS ASSERTS THE IDENTITY OF `0001`, NOT THE HEAD OF THE CHAIN, AND THE
    DIFFERENCE IS THE ENTIRE VALUE OF THE TEST. It used to read
    `scripts.get_current_head() == FIRST_REVISION`, which is the head of the
    whole chain — so the moment Task 4 lands `0002`, this Task 3 test goes red
    with `assert '0002' == '0001'`. MEASURED with a `0002` stub. A test written
    to give Task 4's author a literal to read would instead have handed them a
    failure in somebody else's file, naming the head and saying nothing about
    `0001`, and left them to work out whether their own revision id was wrong.

    `get_base()` is the assertion that stays true forever: `0001` is the base of
    the chain however many revisions follow it. `down_revision is None` is the
    same claim read off the script itself, and both survive `0002`, `0003` and
    everything after.

    The DSN is irrelevant here — this reads the script directory, not a database
    — so a placeholder is passed rather than a fixture requested, which keeps
    this test off the container entirely.
    """
    scripts = ScriptDirectory.from_config(alembic_config("postgresql+psycopg://unused/unused"))

    revision = scripts.get_revision(FIRST_REVISION)
    assert revision.revision == FIRST_REVISION
    assert revision.down_revision is None, "0001 must be the base revision"
    assert scripts.get_base() == FIRST_REVISION, (
        "0001 must remain the base of the chain; a later revision may follow it "
        "but nothing may precede it"
    )


def test_the_migration_creates_exactly_the_expected_tables(
    migrated_database: str, alembic_version_table: str
) -> None:
    """EXACT SET EQUALITY, for the reason Task 2 learned the hard way.

    A count is satisfied by seven wrong tables and a subset check is satisfied by
    seven right ones plus an eighth nobody meant to create. Five decoy roles
    defeated Task 2's cardinality floor in precisely this shape.
    """
    engine = create_engine(migrated_database)
    try:
        with engine.connect() as connection:
            assert _tables(connection) == SKELETON_TABLES | {alembic_version_table}
    finally:
        engine.dispose()


def test_every_table_is_owned_by_the_owner_and_no_login_role_owns_one(
    migrated_database: str, owner_role: str, alembic_version_table: str
) -> None:
    """🔴 THE PROOF TASK 2 COULD NOT WRITE, because no table existed then.

    A table's owner BYPASSES row-level security on it unless the table is
    `FORCE ROW LEVEL SECURITY`. Task 4 will set `FORCE`, and this is the
    assertion that means Task 4 does not have to be the only thing standing
    between a LOGIN role and every tenant's rows: ownership sits on
    `titlepipe_owner`, which nothing can authenticate as.

    TWO ASSERTIONS, AND THE SECOND IS NOT IMPLIED BY THE FIRST. The first names
    the role this repository chose. The second states the PROPERTY that made it
    the right choice, and it would still catch a future migration that moved
    ownership to some new non-login role while `owner_role` was updated to
    match — and, more usefully, one that moved it to `titlepipe_migration`,
    which is the mistake a forgotten `SET ROLE` in `env.py` actually produces.

    The table set is asserted first. Both claims below are `for` loops, and a
    `for` over nothing passes.
    """
    engine = create_engine(migrated_database)
    try:
        with engine.connect() as connection:
            owners = _table_owners(connection)
    finally:
        engine.dispose()

    assert set(owners) == SKELETON_TABLES | {alembic_version_table}

    for table, (owner, can_log_in) in sorted(owners.items()):
        assert owner == owner_role, f"{table} is owned by {owner}, not {owner_role}"
        assert can_log_in is False, (
            f"{table} is owned by {owner}, which can LOG IN. A table's owner "
            f"bypasses RLS unless FORCE is set, so this is a live bypass."
        )


def test_every_tenant_table_carries_its_own_tenant_id_and_the_registry_does_not(
    migrated_database: str,
) -> None:
    """The column contract, per table, as an exact set.

    `tenant_id uuid NOT NULL` on the six is what lets Task 4's policy be
    `tenant_id = …` with no join. `NOT NULL` is asserted because `NULL = <uuid>`
    is NULL rather than true: a nullable column would allow rows no tenant can
    read, none can delete, and no isolation test can see.
    """
    engine = create_engine(migrated_database)
    try:
        with engine.connect() as connection:
            columns = _columns(connection)
    finally:
        engine.dispose()

    for table, expected in sorted(EXPECTED_COLUMNS.items()):
        assert set(columns[table]) == set(expected), f"{table} has the wrong columns"
        assert columns[table]["id"] == ColumnFacts("uuid", False, UUID_DEFAULT)
        assert columns[table]["created_at"] == ColumnFacts("timestamptz", False, NOW_DEFAULT)

    for table in sorted(EXPECTED_COLUMNS.keys() - {"tenants"}):
        assert columns[table]["tenant_id"] == ColumnFacts("uuid", False, None), (
            f"{table}.tenant_id must be uuid NOT NULL; every RLS policy keys on it"
        )

    assert "tenant_id" not in columns["tenants"], (
        "tenants is the registry: its primary key IS the tenant id, and Task 4 "
        "derives the tenant tables from the presence of a tenant_id column"
    )

    # 🔴 NULLABLE, AND THE NULLABILITY IS THE POINT. An engine with no coordinate
    # support declares `null` and never fabricates a box; Reader A is a VLM and
    # genuinely cannot cite one.
    assert columns["field_readings"]["line_coords"] == ColumnFacts("jsonb", True, None)
    # NULL when the field has a value. This is NOT a third NA state — the two NA
    # states are labels of the enum below.
    assert columns["fields"]["na_reason"] == ColumnFacts("na_reason", True, None)


def test_na_reason_has_exactly_four_labels_in_exactly_this_order(
    migrated_database: str,
) -> None:
    """COUNT AND ORDER, ASSERTED SEPARATELY, because they fail separately.

    Adding a fifth label changes the count and leaves the first four in order; a
    tuple comparison alone would report that as an order failure and send the
    reader looking for a reordering that did not happen. Swapping two labels
    leaves the count untouched, so a count alone would not see it at all.

    The expected labels come from `titlepipe_core.db.models`, and the migration
    that created the type repeats them as its own literal — deliberately, since a
    migration is a frozen snapshot. This comparison is the only thing keeping the
    two copies in agreement.

    Order matters to PostgreSQL, not only to us: `enumsortorder` is what `<`,
    `ORDER BY` and `MIN()` on this type use.
    """
    engine = create_engine(migrated_database)
    try:
        with engine.connect() as connection:
            labels = _enum_labels(connection, "na_reason")
    finally:
        engine.dispose()

    assert len(labels) == len(NA_REASON_LABELS), (
        f"na_reason has {len(labels)} labels, expected {len(NA_REASON_LABELS)}: {labels}"
    )
    assert labels == NA_REASON_LABELS, f"na_reason labels are out of order: {labels}"


def test_audit_logs_triggers_are_statement_level_before_and_enabled(
    migrated_database: str,
) -> None:
    """The STATEMENT/ROW/BEFORE/enabled facts, read from the catalog.

    The behavioural tests below are the primary proof and this cannot replace
    them — a trigger that is statement-level, `BEFORE` and enabled but raises
    nothing would satisfy every assertion here and refuse no writes. What this
    adds is DIAGNOSIS: when an append-only test goes red, this says which of the
    four ways it broke.

    That is precisely why `tgenabled` is read. Without it this test could not
    tell "re-declared `FOR EACH ROW`" from "still statement-level, switched off"
    — and `ALTER TABLE audit_log DISABLE TRIGGER ALL` leaves `tgtype` untouched,
    so the old version of this test PASSED with the trigger disabled. A
    diagnostic that is blind to one of the failure modes it exists to
    distinguish is not doing its job.
    """
    engine = create_engine(migrated_database)
    try:
        with engine.connect() as connection:
            triggers = _triggers(connection, "audit_log")
    finally:
        engine.dispose()

    assert set(triggers) == set(EXPECTED_TRIGGERS)
    for name, facts in sorted(triggers.items()):
        assert facts.is_statement_level is True, (
            f"{name} is FOR EACH ROW. A row trigger does not fire when a "
            f"statement matches no rows, and under Task 4's RLS a cross-tenant "
            f"UPDATE matches exactly zero."
        )
        assert facts.is_before is True, (
            f"{name} is an AFTER trigger. The refusal must land before anything is written."
        )
        assert facts.enabled == TRIGGER_ENABLED, (
            f"{name} has tgenabled={facts.enabled!r}, not {TRIGGER_ENABLED!r}. "
            f"A disabled trigger keeps its tgtype and refuses nothing."
        )


def test_audit_log_refuses_an_update_that_matches_no_rows(migrated_database: str) -> None:
    """🔴 THE ZERO-MATCH UPDATE. This is the whole reason the trigger is STATEMENT.

    `FOR EACH ROW` fires once per affected row, so it does not fire at all when a
    statement affects none — and under Task 4's `FORCE ROW LEVEL SECURITY` a
    cross-tenant `UPDATE` matches exactly zero rows. A row-level trigger would
    therefore be SILENT for the case this trigger exists to refuse, and an
    append-only proof written with a MATCHING update would pass while proving
    nothing about the choice.

    The id is a fresh `gen_random_uuid()`, so it matches nothing by construction
    rather than by the table happening to be empty.

    THE SQLSTATE IS ASSERTED, NOT MERELY THAT SOMETHING RAISED. A misspelled
    column in this very test raises too — `42703` — and would otherwise pass as
    proof that the trigger works.
    """
    engine = create_engine(migrated_database)
    try:
        with engine.connect() as connection:
            absent = connection.execute(text("SELECT gen_random_uuid()")).scalar_one()
            with pytest.raises(DBAPIError) as raised:
                connection.execute(
                    text("UPDATE audit_log SET tenant_id = tenant_id WHERE id = :id"),
                    {"id": absent},
                )
            connection.rollback()
    finally:
        engine.dispose()

    assert _sqlstate(raised.value) == APPEND_ONLY_SQLSTATE, (
        f"expected SQLSTATE {APPEND_ONLY_SQLSTATE} from the append-only trigger, "
        f"got {_sqlstate(raised.value)}: {raised.value}"
    )


def test_audit_log_refuses_an_update_that_matches_a_row(migrated_database: str) -> None:
    """The control. This stays green whether the trigger is STATEMENT or ROW.

    That is exactly why it cannot be the proof, and why it is worth keeping
    beside the zero-match test: the two together say that the append-only rule
    holds in both cases, and the zero-match one alone says the trigger is
    statement-level.

    The row is inserted and the whole thing rolled back, so `audit_log` is empty
    again for the next test.
    """
    engine = create_engine(migrated_database)
    try:
        with engine.connect() as connection:
            row_id = connection.execute(
                text("INSERT INTO audit_log (tenant_id) VALUES (gen_random_uuid()) RETURNING id")
            ).scalar_one()

            with pytest.raises(DBAPIError) as raised:
                connection.execute(
                    text("UPDATE audit_log SET tenant_id = tenant_id WHERE id = :id"),
                    {"id": row_id},
                )
            connection.rollback()
    finally:
        engine.dispose()

    assert _sqlstate(raised.value) == APPEND_ONLY_SQLSTATE


def test_audit_log_refuses_delete_and_truncate(migrated_database: str) -> None:
    """Append-only means all three verbs, not just UPDATE.

    `TRUNCATE` needs its own trigger — PostgreSQL rejects a `FOR EACH ROW`
    trigger that names TRUNCATE, so it cannot share one with UPDATE and DELETE
    without making the STATEMENT/ROW decision unrepresentable. Both refusals go
    through the same function and therefore the same SQLSTATE.
    """
    engine = create_engine(migrated_database)
    try:
        with engine.connect() as connection:
            for statement in ("DELETE FROM audit_log", "TRUNCATE audit_log"):
                with pytest.raises(DBAPIError) as raised:
                    connection.execute(text(statement))
                connection.rollback()
                assert _sqlstate(raised.value) == APPEND_ONLY_SQLSTATE, statement
    finally:
        engine.dispose()


def test_upgrade_downgrade_upgrade_is_clean(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    alembic_version_table: str,
) -> None:
    """🔴 THE ROUND TRIP. `migrated_database` already ran the first upgrade.

    A `downgrade` that misses an object is invisible on a fresh database: the
    first `upgrade` works, and only the SECOND one — after a downgrade — finds
    the leftover, as `already exists`. The likeliest such leftover is the ENUM,
    because **`DROP TABLE` does not drop a type**.

    WHAT IS DIFFED IS THE WHOLE `public` SCHEMA, not the table set. This used to
    compare tables and `pg_enum` only, which is blind to a leaked FUNCTION,
    SEQUENCE, VIEW or standalone INDEX — and `0001` creates a function, so one of
    those blind spots was directly in front of it. `_public_schema_objects` is
    the diff, and `alembic_version` plus its own index is the only permitted
    residue: Alembic creates that table outside every revision script and
    `downgrade base` empties rather than drops it. `migrated_database`'s teardown
    removes it by hand for exactly that reason.

    WHY THE POST-DOWNGRADE STATE IS CAPTURED HERE AND ASSERTED LATER. Asserting
    it immediately would be the stronger-reading test and the weaker diagnostic:
    it would fire before the second `upgrade` ever ran, so the failure would be
    this file's assertion message rather than PostgreSQL's own `type "na_reason"
    already exists` — the message that says which object was left behind and is
    the thing a reader can act on. The second `upgrade` is therefore allowed to
    hit the leftover first, and the capture below is the independent check that
    survives if a future downgrade leaves something the re-upgrade happens not to
    collide with.
    """
    config = alembic_config(migration_dsn)

    command.downgrade(config, "base")

    engine = create_engine(migrated_database)
    try:
        with engine.connect() as connection:
            after_downgrade = _public_schema_objects(connection)

        command.upgrade(config, "head")

        with engine.connect() as connection:
            assert _tables(connection) == SKELETON_TABLES | {alembic_version_table}
            assert _enum_labels(connection, "na_reason") == NA_REASON_LABELS
    finally:
        engine.dispose()

    assert after_downgrade == {
        "relations": {f"r:{alembic_version_table}"},
        "indexes": set(),
        "functions": set(),
        "enum_types": set(),
    }, (
        "downgrade did not return `public` to empty. Everything below `relations: "
        f"['r:{alembic_version_table}']` is a leak: {after_downgrade}"
    )


def test_alembic_check_reports_no_difference(
    migrated_database: str, alembic_config: Callable[[str], Config], migration_dsn: str
) -> None:
    """`models.py` and the migrated database agree.

    `command.check` raises `AutogenerateDiffsDetected` when they do not. It is
    genuinely wired — it runs `migrations/env.py`, opens a real connection and
    reflects the real catalog — and the test below is what proves that claim
    rather than asserting it.

    `migrated_database` is requested for ordering, not for its value: `check`
    compares against whatever is in the database, and against an unmigrated one
    it would report seven tables to add and fail for the wrong reason.
    """
    command.check(alembic_config(migration_dsn))


def test_alembic_check_would_notice_a_model_the_database_does_not_have(
    migrated_database: str, alembic_config: Callable[[str], Config], migration_dsn: str
) -> None:
    """The anti-vacuity guard for the test above.

    A `check` that silently did nothing — a broken `target_metadata`, an `env.py`
    that returned before configuring, an exception class that is never raised —
    would leave the test above green forever. So a table is added to
    `Base.metadata` that the database does not have, and `check` must say so.

    `Base.metadata` is process-global, so the table is removed in a `finally`.
    Without that, every later test in this session would see a diff.
    """
    probe = sa.Table(
        "alembic_check_probe", Base.metadata, sa.Column("id", sa.Integer, primary_key=True)
    )
    try:
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(alembic_config(migration_dsn))
    finally:
        Base.metadata.remove(probe)

    # And back to agreeing, proved rather than assumed: the removal above is what
    # every later test in this session depends on.
    command.check(alembic_config(migration_dsn))


# --- `env.py`'s own behaviour ------------------------------------------------
#
# Everything above drives `env.py` down its happy path. What follows covers the
# two paths that END in a `raise`, and the three DSN sources it declares.
#
# The offline refusal is the ONE PLACE IN TASK 3 WHERE A SECURITY PROPERTY RESTS
# ON A `raise` RATHER THAN ON THE DATABASE. Everywhere else the `INHERIT FALSE`
# membership does the enforcing: forget `SET ROLE` and PostgreSQL refuses. In
# `--sql` mode there is no connection to refuse anything, so Alembic would
# cheerfully emit seven `CREATE TABLE`s that a DBA executes as themselves,
# producing exactly the LOGIN-role ownership `roles.sql` exists to make
# impossible. CONFIRMED: replacing `run_migrations_offline`'s body with an
# ordinary implementation left the suite at 124 passed. Nothing was testing it.


def test_offline_sql_mode_is_refused(
    alembic_config: Callable[[str], Config], migration_dsn: str
) -> None:
    """`--sql` must refuse, because it cannot `SET ROLE`.

    The refusal names the role, so the operator is told what the generated script
    would have got wrong rather than merely that this is unsupported.

    No database is touched: the refusal happens before any engine is built, which
    is also why this test does not request `migrated_database`.
    """
    with pytest.raises(RuntimeError) as raised:
        command.upgrade(alembic_config(migration_dsn), "head", sql=True)

    message = str(raised.value)
    assert "offline" in message
    assert "titlepipe_owner" in message


def test_a_config_naming_no_database_anywhere_is_refused(
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """All three sources empty is a configuration error, and says so.

    Alembic's own behaviour for a missing URL is to build an engine from the
    empty string, which fails somewhere inside SQLAlchemy with a message about a
    driver. The refusal names all three places a DSN can come from, because the
    person reading it is the person who has to supply one.
    """
    monkeypatch.delenv(DATABASE_URL_VARIABLE, raising=False)
    config = alembic_config(migration_dsn)
    del config.attributes[ALEMBIC_DSN_ATTRIBUTE]

    with pytest.raises(RuntimeError) as raised:
        command.upgrade(config, "head")

    message = str(raised.value)
    assert DATABASE_URL_VARIABLE in message
    assert "alembic.ini" in message
    assert ALEMBIC_DSN_ATTRIBUTE in message


def test_an_unreachable_dsn_really_does_fail(
    alembic_config: Callable[[str], Config], monkeypatch: pytest.MonkeyPatch
) -> None:
    """The control for the three precedence tests below.

    Each of those points the LOSING sources at `UNREACHABLE_DSN` and asserts the
    command succeeds. That proves nothing unless the unreachable DSN genuinely
    fails — a typo making it reachable, or an `env.py` that silently fell back to
    something else, would make all three pass while checking no precedence at
    all.
    """
    monkeypatch.setenv(DATABASE_URL_VARIABLE, UNREACHABLE_DSN)
    config = alembic_config(UNREACHABLE_DSN)

    with pytest.raises(OperationalError):
        command.check(config)


def test_the_caller_attribute_beats_the_environment(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`config.attributes["dsn"]` wins over `TITLEPIPE_DATABASE_URL`.

    This is the precedence the test suite itself depends on: a developer with
    `TITLEPIPE_DATABASE_URL` exported for their own cluster must not have the
    harness quietly migrate it. `command.check` is the probe because it connects
    and reflects without changing anything.
    """
    monkeypatch.setenv(DATABASE_URL_VARIABLE, UNREACHABLE_DSN)

    command.check(alembic_config(migration_dsn))


def test_the_environment_beats_the_ini_file(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`TITLEPIPE_DATABASE_URL` wins over `sqlalchemy.url` in `alembic.ini`.

    This is the deployment path: the committed `alembic.ini` carries no
    credential, and an operator supplies one through the environment. A local
    `sqlalchemy.url` someone left in their working copy must not override it.
    """
    monkeypatch.setenv(DATABASE_URL_VARIABLE, migration_dsn)
    config = alembic_config(migration_dsn)
    del config.attributes[ALEMBIC_DSN_ATTRIBUTE]
    config.set_main_option("sqlalchemy.url", UNREACHABLE_DSN)

    command.check(config)


def test_the_ini_file_is_used_when_nothing_else_names_a_database(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The third source works at all.

    `alembic.ini` ships with no `sqlalchemy.url` — a DSN there would be
    `titlepipe_migration`'s credential in version control — so this is the slot an
    operator may fill locally, and it is declared, so it is tested.

    `set_main_option` goes through `ConfigParser`, where a `%` in a password
    begins an interpolation and raises. The generated migration password is
    `token_urlsafe` and has none, which is exactly why `config.attributes` (a
    plain dict) is the mechanism the harness itself uses.
    """
    monkeypatch.delenv(DATABASE_URL_VARIABLE, raising=False)
    config = alembic_config(migration_dsn)
    del config.attributes[ALEMBIC_DSN_ATTRIBUTE]
    config.set_main_option("sqlalchemy.url", migration_dsn)

    command.check(config)


def test_a_failed_upgrade_leaves_no_partial_schema_behind(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    alembic_version_table: str,
    tmp_path: Path,
) -> None:
    """🔴 THE WHOLE UPGRADE IS ONE TRANSACTION, ASSERTED RATHER THAN COMMENTED.

    `alembic.ini` used to merely claim `transaction_per_migration` was left at
    its default. A claim in a comment is not a control, and this is the property
    it was claiming: a chain of revisions applied by one `upgrade` either all
    land or none do.

    Proved with a `0002` that creates a table and then executes nonsense. If the
    chain were per-migration, `0001`'s seven tables would survive the failure and
    the assertion below would find them. Because it is one transaction, `public`
    comes back with nothing but Alembic's own version table.

    This also demonstrates the case `migrated_database`'s teardown was restructured
    for: an upgrade that fails part way now still gets a teardown, because the
    `command.upgrade` call lives inside the fixture's `try`.

    The probe revision is written to a `tmp_path` and reached through
    `version_locations`, so nothing is ever created in `migrations/versions/` and
    a crash here cannot leave a stray revision behind for the next run.
    """
    (tmp_path / "0002_probe.py").write_text(_FAILING_REVISION, encoding="utf-8")

    real_config = alembic_config(migration_dsn)
    versions = Path(str(real_config.get_main_option("script_location"))) / "versions"

    probe_config = alembic_config(migration_dsn)
    # `path_separator`, not the older `version_path_separator` — alembic 1.18.5
    # emits a `DeprecationWarning` for the latter, and this suite runs with
    # `-W` defaults where a warning is noise that trains people to ignore
    # warnings.
    probe_config.set_main_option("path_separator", "os")
    probe_config.set_main_option("version_locations", f"{versions}{os.pathsep}{tmp_path}")

    command.downgrade(real_config, "base")
    try:
        with pytest.raises(DBAPIError):
            command.upgrade(probe_config, "head")

        engine = create_engine(migrated_database)
        try:
            with engine.connect() as connection:
                surviving = _public_schema_objects(connection)
        finally:
            engine.dispose()

        assert surviving["relations"] <= {f"r:{alembic_version_table}"}, (
            "a failed upgrade left objects behind, so the revisions are NOT "
            f"running in one transaction: {sorted(surviving['relations'])}"
        )
        assert surviving["functions"] == set()
        assert surviving["enum_types"] == set()
    finally:
        # Back to head for the rest of the module, and for the fixture's own
        # teardown, which downgrades from wherever this left things.
        command.upgrade(real_config, "head")


# A revision that creates something and then fails, used only by the test above.
# It lives as a string rather than a file in `migrations/versions/` because a
# real file there would be picked up by every ordinary `upgrade` in the suite.
_FAILING_REVISION = '''"""A revision that fails after creating a table. Test fixture only."""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE TABLE partial_upgrade_probe (id integer)")
    op.execute("SELECT this_function_does_not_exist()")


def downgrade() -> None:
    op.execute("DROP TABLE partial_upgrade_probe")
'''
