"""Migration `0001`, read back from the live catalog rather than from the file.

The database is an EPHEMERAL CONTAINER — see `conftest.py`'s database seam. The
migration is applied by the module-scoped `migrated_database` fixture, which
also puts the database back exactly as it found it; that teardown is not
housekeeping, and its docstring says what breaks without it.

Nothing here is skipped. If Docker or `psql` is unavailable these tests FAIL.

THE CONTAINMENT LESSON FROM TASK 2 APPLIES TO EVERY ENUMERATION BELOW. Five
decoy roles satisfied a `>= 5` cardinality floor while two real roles were
missing, and a table enumeration is satisfied by the wrong seven tables just as
readily as by the right ones. So each enumeration asserts an EXACT SET — of
table names, of column names per table, of enum labels in order, of trigger
names — never a count and never a subset.
"""

from __future__ import annotations

import argparse
import logging
import os
from collections.abc import Callable
from pathlib import Path
from typing import NamedTuple

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Connection, Engine, text
from sqlalchemy.exc import DBAPIError, OperationalError

from titlepipe_core.db.models import (
    NA_REASON_LABELS,
    NA_REASON_TYPE_NAME,
    NAMING_CONVENTION,
    Base,
)

# The exact seven. `alembic_version` is asserted alongside them rather than
# filtered out: it is created outside every revision script, it is the one table
# nobody writes a `CREATE TABLE` for, and Task 2 cared specifically that it lands
# on the owner like everything else.
SKELETON_TABLES = frozenset(
    {"tenants", "orders", "packages", "pages", "fields", "field_readings", "audit_log"}
)

# Every skeleton table has these two.
IDENTITY_COLUMNS = frozenset({"id", "created_at"})

# 🔴 `tenants` HAS NO `tenant_id` AND THAT IS THE CONTRACT, not an omission. It
# is the registry: its primary key *is* the tenant id, so Task 4's policy keys on
# `id` there. Task 4 derives which tables are tenant tables from the presence of
# this column, so an extra one here would silently give the registry the wrong
# policy.
EXPECTED_COLUMNS: dict[str, frozenset[str]] = {
    "tenants": IDENTITY_COLUMNS,
    "orders": IDENTITY_COLUMNS | {"tenant_id"},
    "packages": IDENTITY_COLUMNS | {"tenant_id"},
    "pages": IDENTITY_COLUMNS | {"tenant_id"},
    "fields": IDENTITY_COLUMNS | {"tenant_id", "na_reason"},
    "field_readings": IDENTITY_COLUMNS | {"tenant_id", "line_coords"},
    "audit_log": IDENTITY_COLUMNS | {"tenant_id"},
}

# 🔴 THE PRIMARY KEY OF EVERY TABLE, BY NAME AND BY KEY COLUMNS IN KEY ORDER.
#
# MEASURED 2026-08-05 on the tree before this constant existed: removing EVERY
# `sa.PrimaryKeyConstraint` from `0001` left the suite at `159 passed`. Nothing
# read a primary key at all — `alembic check` does not compare them, `_columns`
# reads only `information_schema.columns`, and the index set is asserted only
# after a downgrade, where it must be empty. The whole skeleton could have
# shipped with no primary key on any table.
#
# THE ORDER IS NOT DECORATION. `(tenant_id, id)` on the six closes a cross-tenant
# existence oracle that `(id)` alone opens under `0002`'s
# `FORCE ROW LEVEL SECURITY`: unique enforcement runs before the policy's
# `WITH CHECK`, so an insert of an id held by another tenant fails as a duplicate
# key while an insert of an unheld id succeeds — two distinguishable answers
# about rows the caller cannot read or count. `migrations/versions/0001_skeleton
# .py::_tenant_primary_key` holds the measurement. A test that compared key
# columns as a SET would pass with the prefix reversed, and the prefix is the
# whole point.
#
# `tenants` is `(id)` because its `id` IS a tenant id.
EXPECTED_PRIMARY_KEYS: dict[str, tuple[str, ...]] = {
    "tenants": ("id",),
    "orders": ("tenant_id", "id"),
    "packages": ("tenant_id", "id"),
    "pages": ("tenant_id", "id"),
    "fields": ("tenant_id", "id"),
    "field_readings": ("tenant_id", "id"),
    "audit_log": ("tenant_id", "id"),
}

EXPECTED_TRIGGERS = frozenset({"audit_log_append_only", "audit_log_no_truncate"})

# `pg_trigger.tgenabled` for an ordinary, firing trigger. The other three values
# — `'D'` disabled, `'R'` replica, `'A'` always — all change when the trigger
# fires, and `'D'` means never.
TRIGGER_ENABLED = "O"

# The two server defaults every skeleton table carries, as PostgreSQL renders
# them back. Read from the catalog rather than assumed: `tenants` is seeded by
# Task 6, which supplies no `id`, so its default is the only thing producing one.
UUID_DEFAULT = "gen_random_uuid()"
NOW_DEFAULT = "now()"

# `feature_not_supported`, raised by the trigger. Asserted instead of "something
# raised", because a typo'd column raises too — as `42703`, and a typo'd table as
# `42P01`. Neither can be mistaken for this one.
APPEND_ONLY_SQLSTATE = "0A000"

# `undefined_function`, which is what `_FAILING_REVISION`'s deliberate nonsense
# raises. See `test_a_failed_upgrade_leaves_no_partial_schema_behind` for why
# `pytest.raises(DBAPIError)` alone made that test vacuous.
UNDEFINED_FUNCTION_SQLSTATE = "42883"

FIRST_REVISION = "0001"

# `migrations/env.py`'s three DSN sources, in the order it consults them.
DATABASE_URL_VARIABLE = "TITLEPIPE_DATABASE_URL"
ALEMBIC_DSN_ATTRIBUTE = "dsn"

# A DSN that resolves and refuses fast. Port 1 on loopback is not listening, so
# every precedence test below fails in milliseconds when the WRONG source wins,
# and never reaches a real server.
#
# Host and port are their own constants because
# `test_an_unreachable_dsn_really_does_fail` asserts that the failure names THIS
# server — see that test — and a literal repeated in the assertion could drift
# from the literal in the DSN without anything noticing.
UNREACHABLE_HOST = "127.0.0.1"
UNREACHABLE_PORT = 1
UNREACHABLE_DSN = (
    f"postgresql+psycopg://nobody:nobody@{UNREACHABLE_HOST}:{UNREACHABLE_PORT}/nowhere"
)

# For the tests that drive `env.py` down a path that RAISES before any engine is
# built. They need a syntactically valid DSN and nothing more, so they take this
# instead of `migration_dsn` — which is a session fixture that STARTS THE
# CONTAINER. `test_the_first_revision_id_is_the_literal_0001` set the pattern.
PLACEHOLDER_DSN = "postgresql+psycopg://unused/unused"

# `migrations/versions/0001_skeleton.py`, read as text by the two tests that can
# only assert on the source. See `test_the_migration_source_refuses_the_forgiving
# _spellings` for what makes a source assertion the honest option there.
MIGRATION_SOURCE = (
    Path(__file__).resolve().parent.parent / "migrations" / "versions" / "0001_skeleton.py"
)


def _tables(connection: Connection) -> set[str]:
    """Ordinary tables in `public`. Views, sequences and indexes are not tables."""
    result = connection.execute(
        text(
            "SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE n.nspname = 'public' AND c.relkind = 'r'"
        )
    )
    return {str(row[0]) for row in result}


def _table_owners(connection: Connection) -> dict[str, tuple[str, bool]]:
    """table -> (owner role, whether that role can log in).

    `pg_roles` rather than `pg_authid` for `rolcanlogin`: the view carries it and
    is readable without a superuser, so this assertion does not depend on which
    DSN it is handed.
    """
    result = connection.execute(
        text(
            "SELECT c.relname, r.rolname, r.rolcanlogin "
            "FROM pg_class c "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            "JOIN pg_roles r ON r.oid = c.relowner "
            "WHERE n.nspname = 'public' AND c.relkind = 'r'"
        )
    )
    return {str(row[0]): (str(row[1]), bool(row[2])) for row in result}


class ColumnFacts(NamedTuple):
    """Type, nullability and server default — the three things a skeleton column is.

    `default` was not read at all until review pointed it out, so six of seven
    tables' defaults were unverified. It is not decoration: Task 6 seeds
    `tenants` without supplying an `id`, so `gen_random_uuid()` is the only thing
    producing one, and a migration that dropped the default would surface there
    as a `NOT NULL` violation in somebody else's task.
    """

    type_name: str
    nullable: bool
    default: str | None


def _columns(connection: Connection) -> dict[str, dict[str, ColumnFacts]]:
    """table -> column -> `ColumnFacts`.

    `udt_name` rather than `data_type`: `data_type` reports `USER-DEFINED` for an
    enum and `ARRAY` for anything array-shaped, so it cannot tell `na_reason`
    from any other user-defined type.
    """
    result = connection.execute(
        text(
            "SELECT table_name, column_name, udt_name, is_nullable, column_default "
            "FROM information_schema.columns WHERE table_schema = 'public'"
        )
    )
    columns: dict[str, dict[str, ColumnFacts]] = {}
    for row in result:
        columns.setdefault(str(row[0]), {})[str(row[1])] = ColumnFacts(
            str(row[2]), str(row[3]) == "YES", None if row[4] is None else str(row[4])
        )
    return columns


class PrimaryKeyFacts(NamedTuple):
    """The constraint's name, and its key columns IN KEY ORDER.

    A `tuple` and not a `frozenset`, deliberately. `(tenant_id, id)` and
    `(id, tenant_id)` are the same set and different keys: only the first
    tenant-prefixes the backing index, and only the first is what
    `_tenant_primary_key` measured. A set comparison would pass with the prefix
    reversed.
    """

    name: str
    columns: tuple[str, ...]


def _primary_keys(connection: Connection) -> dict[str, PrimaryKeyFacts]:
    """table -> `PrimaryKeyFacts`, read from `pg_constraint`.

    `pg_constraint.conkey` is a `smallint[]` of attribute numbers IN KEY ORDER,
    and `pg_attribute` is keyed on `(attrelid, attnum)` — so the join has to
    carry the ordinal through `WITH ORDINALITY` and aggregate on it. Joining on
    `a.attnum = ANY(c.conkey)` instead would return the columns in whatever order
    the planner produced them, which is exactly the assertion this exists to
    make.

    A table with no primary key contributes no row, so it is simply absent from
    the mapping — which is why the caller asserts the KEY SET as well as the
    values.
    """
    result = connection.execute(
        text(
            "SELECT c.conrelid::regclass::text, c.conname, "
            "       array_agg(a.attname ORDER BY k.ord) "
            "FROM pg_constraint c "
            "JOIN LATERAL unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord) ON true "
            "JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum "
            "WHERE c.contype = 'p' AND c.connamespace = 'public'::regnamespace "
            "GROUP BY 1, 2"
        )
    )
    return {
        str(row[0]): PrimaryKeyFacts(str(row[1]), tuple(str(column) for column in row[2]))
        for row in result
    }


def _public_schema_objects(connection: Connection, version_table: str) -> dict[str, set[str]]:
    """Everything in `public` that a migration could have created and left behind.

    Broader than the table set on purpose. The round trip used to diff tables and
    `pg_enum` only, so a downgrade that leaked a FUNCTION, a SEQUENCE, a VIEW or
    a standalone INDEX was invisible to it — and `0001` creates a function, which
    is exactly one of the blind spots.

    Indexes belonging to `alembic_version` are excluded: that table survives
    `downgrade base` by design, so its primary-key index does too, and its name
    is Alembic's to choose rather than ours to hardcode.

    `version_table` is a PARAMETER rather than the literal `"alembic_version"`
    this function used to carry. Four tests in this file already take the
    `alembic_version_table` fixture and then called a helper that ignored it, so
    the name existed in two places and only one of them was the seam.
    """
    relations = connection.execute(
        text(
            "SELECT c.relkind, c.relname FROM pg_class c "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE n.nspname = 'public' AND c.relkind IN ('r', 'S', 'v', 'm', 'p', 'f')"
        )
    )
    indexes = connection.execute(
        text(
            "SELECT indexname FROM pg_indexes "
            "WHERE schemaname = 'public' AND tablename <> :version_table"
        ),
        {"version_table": version_table},
    )
    functions = connection.execute(
        text(
            "SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace "
            "WHERE n.nspname = 'public'"
        )
    )
    enum_types = connection.execute(
        text(
            "SELECT t.typname FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace "
            "WHERE n.nspname = 'public' AND t.typtype = 'e'"
        )
    )
    return {
        "relations": {f"{row[0]}:{row[1]}" for row in relations},
        "indexes": {str(row[0]) for row in indexes},
        "functions": {str(row[0]) for row in functions},
        "enum_types": {str(row[0]) for row in enum_types},
    }


def _enum_labels(connection: Connection, type_name: str) -> tuple[str, ...]:
    """The type's labels in `enumsortorder`, or `()` when the type does not exist.

    `ORDER BY e.enumsortorder` is the server's own ordering, which is what a
    comparison, a `<` and a `MIN()` over the type would use. Reading the rows
    unordered and sorting them here would make the order assertion vacuous.
    """
    result = connection.execute(
        text(
            "SELECT e.enumlabel FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid "
            "WHERE t.typname = :type_name ORDER BY e.enumsortorder"
        ),
        {"type_name": type_name},
    )
    return tuple(str(row[0]) for row in result)


class TriggerFacts(NamedTuple):
    """What has to be true of an append-only trigger for it to be one.

    All three, because each can be broken without touching the others, and
    breaking any one of them switches the protection off:

    * `is_statement_level` — `tgtype & 1` is `TRIGGER_TYPE_ROW`. A row trigger
      does not fire when a statement matches nothing, which is exactly the case
      under Task 4's RLS;
    * `is_before` — `tgtype & 2` is `TRIGGER_TYPE_BEFORE`. `0001` calls this
      load-bearing ("so nothing is written before the refusal") and until now
      nothing asserted it;
    * `enabled` — `tgenabled`, which was NOT being read at all. MEASURED
      2026-08-05: `titlepipe_migration` with `SET ROLE titlepipe_owner` can issue
      `ALTER TABLE audit_log DISABLE TRIGGER ALL`, after which `tgenabled` is
      `'D'` and **`tgtype` is unchanged** — so a check on `tgtype` alone passes
      with the trigger switched off. `'O'` is "fires in origin/local
      replication role", which is the ordinary enabled state.
    """

    is_statement_level: bool
    is_before: bool
    enabled: str


def _triggers(connection: Connection, table: str) -> dict[str, TriggerFacts]:
    """trigger name -> the three facts above.

    `tgisinternal` triggers are the ones PostgreSQL creates for constraints; they
    are not ours and would make an exact-set assertion impossible to write.
    """
    result = connection.execute(
        text(
            "SELECT t.tgname, (t.tgtype & 1) = 0, (t.tgtype & 2) <> 0, t.tgenabled "
            "FROM pg_trigger t "
            "JOIN pg_class c ON c.oid = t.tgrelid "
            "WHERE c.relname = :table AND NOT t.tgisinternal"
        ),
        {"table": table},
    )
    return {str(row[0]): TriggerFacts(bool(row[1]), bool(row[2]), str(row[3])) for row in result}


def _sqlstate(error: DBAPIError) -> str | None:
    """The five-character SQLSTATE psycopg attached, if it attached one.

    Checked with `isinstance` rather than trusted: `getattr` on a DBAPI exception
    returns whatever is there, and a test that compared `Any` to a string would
    pass for a `None` as readily as for a code.
    """
    sqlstate = getattr(error.orig, "sqlstate", None)
    return sqlstate if isinstance(sqlstate, str) else None


def test_the_first_revision_id_is_the_literal_0001(alembic_config: Callable[[str], Config]) -> None:
    """Task 4's `0002` sets `down_revision = "0001"`, so the id is a contract.

    Alembic's default is a random hash. A hash would work exactly as well for
    Alembic and not at all for the person writing `0002`, who would have to look
    it up and would have nothing to notice if they looked up the wrong one.

    🔴 THIS ASSERTS THE IDENTITY OF `0001`, NOT THE HEAD OF THE CHAIN, AND THE
    DIFFERENCE IS THE ENTIRE VALUE OF THE TEST. It used to read
    `scripts.get_current_head() == FIRST_REVISION`, which is the head of the
    whole chain — so the moment Task 4 lands `0002`, this Task 3 test goes red
    with `assert '0002' == '0001'`. MEASURED with a `0002` stub. A test written
    to give Task 4's author a literal to read would instead have handed them a
    failure in somebody else's file, naming the head and saying nothing about
    `0001`, and left them to work out whether their own revision id was wrong.

    `get_base()` is the assertion that stays true forever: `0001` is the base of
    the chain however many revisions follow it. `down_revision is None` is the
    same claim read off the script itself, and both survive `0002`, `0003` and
    everything after.

    The DSN is irrelevant here — this reads the script directory, not a database
    — so a placeholder is passed rather than a fixture requested, which keeps
    this test off the container entirely.
    """
    scripts = ScriptDirectory.from_config(alembic_config("postgresql+psycopg://unused/unused"))

    revision = scripts.get_revision(FIRST_REVISION)
    assert revision.revision == FIRST_REVISION
    assert revision.down_revision is None, "0001 must be the base revision"
    assert scripts.get_base() == FIRST_REVISION, (
        "0001 must remain the base of the chain; a later revision may follow it "
        "but nothing may precede it"
    )


def test_the_migration_creates_exactly_the_expected_tables(
    migrated_database: str, alembic_version_table: str, seam_engine: Callable[[str], Engine]
) -> None:
    """EXACT SET EQUALITY, for the reason Task 2 learned the hard way.

    A count is satisfied by seven wrong tables and a subset check is satisfied by
    seven right ones plus an eighth nobody meant to create. Five decoy roles
    defeated Task 2's cardinality floor in precisely this shape.
    """
    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            assert _tables(connection) == SKELETON_TABLES | {alembic_version_table}
    finally:
        engine.dispose()


def test_every_table_is_owned_by_the_owner_and_no_login_role_owns_one(
    migrated_database: str,
    owner_role: str,
    alembic_version_table: str,
    seam_engine: Callable[[str], Engine],
) -> None:
    """🔴 THE PROOF TASK 2 COULD NOT WRITE, because no table existed then.

    A table's owner BYPASSES row-level security on it unless the table is
    `FORCE ROW LEVEL SECURITY`. Task 4 will set `FORCE`, and this is the
    assertion that means Task 4 does not have to be the only thing standing
    between a LOGIN role and every tenant's rows: ownership sits on
    `titlepipe_owner`, which nothing can authenticate as.

    TWO ASSERTIONS, AND THE SECOND IS NOT IMPLIED BY THE FIRST. The first names
    the role this repository chose. The second states the PROPERTY that made it
    the right choice, and it would still catch a future migration that moved
    ownership to some new non-login role while `owner_role` was updated to
    match — and, more usefully, one that moved it to `titlepipe_migration`,
    which is the mistake a forgotten `SET ROLE` in `env.py` actually produces.

    The table set is asserted first. Both claims below are `for` loops, and a
    `for` over nothing passes.
    """
    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            owners = _table_owners(connection)
    finally:
        engine.dispose()

    assert set(owners) == SKELETON_TABLES | {alembic_version_table}

    for table, (owner, can_log_in) in sorted(owners.items()):
        assert owner == owner_role, f"{table} is owned by {owner}, not {owner_role}"
        assert can_log_in is False, (
            f"{table} is owned by {owner}, which can LOG IN. A table's owner "
            f"bypasses RLS unless FORCE is set, so this is a live bypass."
        )


def test_every_tenant_table_carries_its_own_tenant_id_and_the_registry_does_not(
    migrated_database: str, seam_engine: Callable[[str], Engine]
) -> None:
    """The column contract, per table, as an exact set.

    `tenant_id uuid NOT NULL` on the six is what lets Task 4's policy be
    `tenant_id = …` with no join. `NOT NULL` is asserted because `NULL = <uuid>`
    is NULL rather than true: a nullable column would allow rows no tenant can
    read, none can delete, and no isolation test can see.
    """
    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            columns = _columns(connection)
    finally:
        engine.dispose()

    for table, expected in sorted(EXPECTED_COLUMNS.items()):
        assert set(columns[table]) == set(expected), f"{table} has the wrong columns"
        assert columns[table]["id"] == ColumnFacts("uuid", False, UUID_DEFAULT)
        assert columns[table]["created_at"] == ColumnFacts("timestamptz", False, NOW_DEFAULT)

    for table in sorted(EXPECTED_COLUMNS.keys() - {"tenants"}):
        assert columns[table]["tenant_id"] == ColumnFacts("uuid", False, None), (
            f"{table}.tenant_id must be uuid NOT NULL; every RLS policy keys on it"
        )

    assert "tenant_id" not in columns["tenants"], (
        "tenants is the registry: its primary key IS the tenant id, and Task 4 "
        "derives the tenant tables from the presence of a tenant_id column"
    )

    # 🔴 NULLABLE, AND THE NULLABILITY IS THE POINT. An engine with no coordinate
    # support declares `null` and never fabricates a box; Reader A is a VLM and
    # genuinely cannot cite one.
    assert columns["field_readings"]["line_coords"] == ColumnFacts("jsonb", True, None)
    # NULL when the field has a value. This is NOT a third NA state — the two NA
    # states are labels of the enum below.
    assert columns["fields"]["na_reason"] == ColumnFacts(NA_REASON_TYPE_NAME, True, None)


def test_every_table_has_the_primary_key_it_is_supposed_to_have(
    migrated_database: str, alembic_version_table: str, seam_engine: Callable[[str], Engine]
) -> None:
    """🔴 THAT THERE IS A PRIMARY KEY AT ALL, WHAT IS IN IT, IN WHAT ORDER, AND
    WHAT IT IS CALLED. NONE OF THE FOUR WAS ASSERTED ANYWHERE.

    MEASURED 2026-08-05: deleting EVERY `sa.PrimaryKeyConstraint` from
    `0001_skeleton.py` left the suite at `159 passed`. `alembic check` does not
    compare primary keys, `_columns` reads only `information_schema.columns`, and
    the index set is asserted only after a downgrade, where it must be empty.

    THE KEY COLUMNS ARE COMPARED AS AN ORDERED TUPLE. `(tenant_id, id)` and
    `(id, tenant_id)` are the same set and are not the same key: only the first
    tenant-prefixes the backing index, and only the first is the one whose
    cross-tenant existence oracle was measured — see `EXPECTED_PRIMARY_KEYS` and
    `0001_skeleton.py::_tenant_primary_key`. A set comparison here would pass
    with the prefix reversed, which is the mutation most likely to happen by
    accident.

    THE CONSTRAINT NAME IS ASSERTED TOO, and that is the only thing in this suite
    that exercises `NAMING_CONVENTION`'s wiring. MEASURED on the same tree:
    deleting `naming_convention=NAMING_CONVENTION` from `Base.metadata` and
    changing the `pk` pattern to PostgreSQL's own `%(table_name)s_pkey` each left
    the suite green, because `alembic check` compares constraints by structure
    and never by name. `test_the_naming_convention_is_exactly_these_five_patterns`
    covers the four patterns that name no constraint yet.

    `alembic_version` is excluded rather than asserted: Alembic creates that
    table outside every revision script and its constraint is Alembic's to name.
    """
    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            keys = _primary_keys(connection)
    finally:
        engine.dispose()

    # THE KEY SET FIRST. A table with no primary key contributes no row to
    # `pg_constraint`, so it is simply missing here — and the loop below is a
    # `for`, which passes over nothing.
    assert set(keys) - {alembic_version_table} == set(EXPECTED_PRIMARY_KEYS), (
        f"these tables have a primary key: {sorted(keys)}; expected "
        f"{sorted({*EXPECTED_PRIMARY_KEYS, alembic_version_table})}"
    )

    for table, expected_columns in sorted(EXPECTED_PRIMARY_KEYS.items()):
        assert keys[table].columns == expected_columns, (
            f"{table}'s primary key is {keys[table].columns}, not {expected_columns}. "
            f"Key ORDER is load-bearing: a tenant table whose key does not LEAD with "
            f"tenant_id answers cross-tenant existence questions through duplicate-key "
            f"errors that RLS cannot suppress."
        )
        assert keys[table].name == f"pk_{table}", (
            f"{table}'s primary key is called {keys[table].name!r}, not 'pk_{table}'. "
            f"NAMING_CONVENTION's `pk` entry is what produces that name, and nothing "
            f"else in this suite reads it back."
        )


def test_the_naming_convention_is_exactly_these_five_patterns() -> None:
    """The four patterns no constraint uses yet, pinned as literals.

    MEASURED 2026-08-05: narrowing `ix` from `%(column_0_N_name)s` to
    `%(column_0_name)s` left the suite at `159 passed`, as did deleting the whole
    convention from `Base.metadata`. The skeleton has nothing but primary keys,
    so `ix`, `uq`, `ck` and `fk` name no live object and no catalog read can
    reach them — the day one of them is wrong is the day a constraint is created
    with the wrong name, and by then renaming it is a migration.

    🔴 WRITTEN OUT RATHER THAN READ BACK FROM `NAMING_CONVENTION`. A test that
    builds its expectation from the constant under test moves whenever the
    constant does and pins nothing at all — the same reason
    `scripts/tests/test_check_backend_rules.py::test_the_line_cap_is_exactly_where
    _it_says_it_is` writes `assert MAX_FILE_LINES == 400` instead of taking the
    number from the module. That was the first version of that test, and it
    survived exactly the mutation it was written to catch.

    `%(column_0_N_name)s` and not `%(column_0_name)s`: the `N` form spans every
    column of a multi-column constraint, so a two-column unique constraint cannot
    collide with a one-column one that happens to start on the same column. `ck`
    is the one that takes `%(constraint_name)s`, because a CHECK has no columns
    of its own to name it after.

    `pk` is here for completeness and is the one entry the DATABASE also proves —
    `test_every_table_has_the_primary_key_it_is_supposed_to_have` reads
    `pk_<table>` out of `pg_constraint`. The other four have only this.
    """
    assert NAMING_CONVENTION == {
        "ix": "ix_%(table_name)s_%(column_0_N_name)s",
        "uq": "uq_%(table_name)s_%(column_0_N_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }

    # And that it is actually ON the metadata every model and every autogenerate
    # run goes through. The patterns being right is worth nothing if the
    # `MetaData` was built without them, and deleting that keyword argument was
    # one of the mutations that survived.
    assert Base.metadata.naming_convention == NAMING_CONVENTION


def test_na_reason_has_exactly_four_labels_in_exactly_this_order(
    migrated_database: str, seam_engine: Callable[[str], Engine]
) -> None:
    """TWO DIFFERENT CLAIMS, AND UNTIL NOW ONLY ONE OF THEM WAS HERE.

    ---------------------------------------------------------------------------
    🔴 THE FOUR LABELS ARE WRITTEN OUT AS A LITERAL, AND THAT IS THE WHOLE POINT
       OF THE FIRST ASSERTION.
    ---------------------------------------------------------------------------
    Everything below the literal compares the live `pg_enum` against
    `NA_REASON_LABELS` IMPORTED FROM THE MODULE UNDER TEST — and the live type
    was created from the migration's verbatim copy of that same tuple. Derived
    against derived. MEASURED 2026-08-05, renaming the labels in BOTH
    `models.py` and `0001_skeleton.py`:

        NA_REASON_LABELS = ("NA", "NOT_FOUND", "NOT_STATED", "ALSO_NA")
        -> 159 passed

    Reordering both copies and adding a fifth to both survive the same way. The
    test's NAME promised four labels in an exact order and its BODY pinned
    neither. This is the same shape as
    `scripts/tests/test_check_backend_rules.py::test_the_line_cap_is_exactly_where
    _it_says_it_is`, which writes `assert MAX_FILE_LINES == 400` rather than
    building its fixture from the constant, for exactly this reason: a fixture
    built from the constant moves whenever the constant does and pins nothing at
    all.

    The rename above is not a hypothetical mutation. `NOT_PRESENT` and
    `PRESENT_UNREADABLE` are a CLAUDE.md hard rule — "the field is not on the
    page" and "the field is on the page and the ink is gone" lead to different
    work — and collapsing them into one `NA` is precisely what the literal now
    refuses.

    THE MIGRATION-VERSUS-MODEL CHECK IS KEPT, because it catches what the literal
    cannot: an edit to ONE of the two copies. A migration is a frozen snapshot
    and `0001` repeats the tuple on purpose, so nothing but this comparison keeps
    the two honest.

    COUNT AND ORDER STAY SEPARATE, because they fail separately. Adding a fifth
    label changes the count and leaves the first four in order; a tuple
    comparison alone would report that as an order failure and send the reader
    looking for a reordering that did not happen. Swapping two labels leaves the
    count untouched, so a count alone would not see it at all. Order matters to
    PostgreSQL and not only to us: `enumsortorder` is what `<`, `ORDER BY` and
    `MIN()` on this type use.
    """
    assert NA_REASON_LABELS == ("NOT_PRESENT", "NOT_FOUND", "NOT_STATED", "PRESENT_UNREADABLE"), (
        "the four labels are a contract, not a variable. NOT_PRESENT and "
        "PRESENT_UNREADABLE must never be collapsed (CLAUDE.md; docs/CONTEXT.md §11)."
    )

    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            labels = _enum_labels(connection, NA_REASON_TYPE_NAME)
    finally:
        engine.dispose()

    assert len(labels) == 4, f"na_reason must have exactly four labels, has {len(labels)}: {labels}"
    assert len(labels) == len(NA_REASON_LABELS), (
        f"na_reason has {len(labels)} labels, expected {len(NA_REASON_LABELS)}: {labels}"
    )
    assert labels == NA_REASON_LABELS, f"na_reason labels are out of order: {labels}"


def test_audit_logs_triggers_are_statement_level_before_and_enabled(
    migrated_database: str, seam_engine: Callable[[str], Engine]
) -> None:
    """The STATEMENT/ROW/BEFORE/enabled facts, read from the catalog.

    The behavioural tests below are the primary proof and this cannot replace
    them — a trigger that is statement-level, `BEFORE` and enabled but raises
    nothing would satisfy every assertion here and refuse no writes. What this
    adds is DIAGNOSIS: when an append-only test goes red, this says which of the
    four ways it broke.

    That is precisely why `tgenabled` is read. Without it this test could not
    tell "re-declared `FOR EACH ROW`" from "still statement-level, switched off"
    — and `ALTER TABLE audit_log DISABLE TRIGGER ALL` leaves `tgtype` untouched,
    so the old version of this test PASSED with the trigger disabled. A
    diagnostic that is blind to one of the failure modes it exists to
    distinguish is not doing its job.
    """
    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            triggers = _triggers(connection, "audit_log")
    finally:
        engine.dispose()

    assert set(triggers) == set(EXPECTED_TRIGGERS)
    for name, facts in sorted(triggers.items()):
        assert facts.is_statement_level is True, (
            f"{name} is FOR EACH ROW. A row trigger does not fire when a "
            f"statement matches no rows, and under Task 4's RLS a cross-tenant "
            f"UPDATE matches exactly zero."
        )
        assert facts.is_before is True, (
            f"{name} is an AFTER trigger. The refusal must land before anything is written."
        )
        assert facts.enabled == TRIGGER_ENABLED, (
            f"{name} has tgenabled={facts.enabled!r}, not {TRIGGER_ENABLED!r}. "
            f"A disabled trigger keeps its tgtype and refuses nothing."
        )


def test_audit_log_refuses_an_update_that_matches_no_rows(
    migrated_database: str, seam_engine: Callable[[str], Engine]
) -> None:
    """🔴 THE ZERO-MATCH UPDATE. This is the whole reason the trigger is STATEMENT.

    `FOR EACH ROW` fires once per affected row, so it does not fire at all when a
    statement affects none — and under Task 4's `FORCE ROW LEVEL SECURITY` a
    cross-tenant `UPDATE` matches exactly zero rows. A row-level trigger would
    therefore be SILENT for the case this trigger exists to refuse, and an
    append-only proof written with a MATCHING update would pass while proving
    nothing about the choice.

    The id is a fresh `gen_random_uuid()`, so it matches nothing by construction
    rather than by the table happening to be empty.

    THE SQLSTATE IS ASSERTED, NOT MERELY THAT SOMETHING RAISED. A misspelled
    column in this very test raises too — `42703` — and would otherwise pass as
    proof that the trigger works.
    """
    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            absent = connection.execute(text("SELECT gen_random_uuid()")).scalar_one()
            with pytest.raises(DBAPIError) as raised:
                connection.execute(
                    text("UPDATE audit_log SET tenant_id = tenant_id WHERE id = :id"),
                    {"id": absent},
                )
            connection.rollback()
    finally:
        engine.dispose()

    assert _sqlstate(raised.value) == APPEND_ONLY_SQLSTATE, (
        f"expected SQLSTATE {APPEND_ONLY_SQLSTATE} from the append-only trigger, "
        f"got {_sqlstate(raised.value)}: {raised.value}"
    )


def test_audit_log_refuses_an_update_that_matches_a_row(
    migrated_database: str, seam_engine: Callable[[str], Engine]
) -> None:
    """The control. This stays green whether the trigger is STATEMENT or ROW.

    That is exactly why it cannot be the proof, and why it is worth keeping
    beside the zero-match test: the two together say that the append-only rule
    holds in both cases, and the zero-match one alone says the trigger is
    statement-level.

    The row is inserted and the whole thing rolled back, so `audit_log` is empty
    again for the next test.
    """
    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            row_id = connection.execute(
                text("INSERT INTO audit_log (tenant_id) VALUES (gen_random_uuid()) RETURNING id")
            ).scalar_one()

            with pytest.raises(DBAPIError) as raised:
                connection.execute(
                    text("UPDATE audit_log SET tenant_id = tenant_id WHERE id = :id"),
                    {"id": row_id},
                )
            connection.rollback()
    finally:
        engine.dispose()

    assert _sqlstate(raised.value) == APPEND_ONLY_SQLSTATE


def test_audit_log_refuses_delete_and_truncate(
    migrated_database: str, seam_engine: Callable[[str], Engine]
) -> None:
    """Append-only means all three verbs, not just UPDATE.

    `TRUNCATE` needs its own trigger — PostgreSQL rejects a `FOR EACH ROW`
    trigger that names TRUNCATE, so it cannot share one with UPDATE and DELETE
    without making the STATEMENT/ROW decision unrepresentable. Both refusals go
    through the same function and therefore the same SQLSTATE.
    """
    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            for statement in ("DELETE FROM audit_log", "TRUNCATE audit_log"):
                with pytest.raises(DBAPIError) as raised:
                    connection.execute(text(statement))
                connection.rollback()
                assert _sqlstate(raised.value) == APPEND_ONLY_SQLSTATE, statement
    finally:
        engine.dispose()


def test_upgrade_downgrade_upgrade_is_clean(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    alembic_version_table: str,
    seam_engine: Callable[[str], Engine],
) -> None:
    """🔴 THE ROUND TRIP. `migrated_database` already ran the first upgrade.

    A `downgrade` that misses an object is invisible on a fresh database: the
    first `upgrade` works, and only the SECOND one — after a downgrade — finds
    the leftover, as `already exists`. The likeliest such leftover is the ENUM,
    because **`DROP TABLE` does not drop a type**.

    WHAT IS DIFFED IS THE WHOLE `public` SCHEMA, not the table set. This used to
    compare tables and `pg_enum` only, which is blind to a leaked FUNCTION,
    SEQUENCE, VIEW or standalone INDEX — and `0001` creates a function, so one of
    those blind spots was directly in front of it. `_public_schema_objects` is
    the diff, and `alembic_version` plus its own index is the only permitted
    residue: Alembic creates that table outside every revision script and
    `downgrade base` empties rather than drops it. `migrated_database`'s teardown
    removes it by hand for exactly that reason.

    WHY THE POST-DOWNGRADE STATE IS CAPTURED HERE AND ASSERTED LATER. Asserting
    it immediately would be the stronger-reading test and the weaker diagnostic:
    it would fire before the second `upgrade` ever ran, so the failure would be
    this file's assertion message rather than PostgreSQL's own `type "na_reason"
    already exists` — the message that says which object was left behind and is
    the thing a reader can act on. The second `upgrade` is therefore allowed to
    hit the leftover first, and the capture below is the independent check that
    survives if a future downgrade leaves something the re-upgrade happens not to
    collide with.
    """
    config = alembic_config(migration_dsn)

    command.downgrade(config, "base")

    engine = seam_engine(migrated_database)
    try:
        with engine.connect() as connection:
            after_downgrade = _public_schema_objects(connection, alembic_version_table)

        command.upgrade(config, "head")

        with engine.connect() as connection:
            assert _tables(connection) == SKELETON_TABLES | {alembic_version_table}
            assert _enum_labels(connection, NA_REASON_TYPE_NAME) == NA_REASON_LABELS
    finally:
        engine.dispose()

    assert after_downgrade == {
        "relations": {f"r:{alembic_version_table}"},
        "indexes": set(),
        "functions": set(),
        "enum_types": set(),
    }, (
        "downgrade did not return `public` to empty. Everything below `relations: "
        f"['r:{alembic_version_table}']` is a leak: {after_downgrade}"
    )


def test_the_migration_source_refuses_the_forgiving_spellings() -> None:
    """🔴 A SOURCE ASSERTION, AND IT IS LABELLED ONE BECAUSE THAT IS WHAT IT IS.

    Two guards in `0001` exist to turn a FORGOTTEN `downgrade` line into a loud
    failure on the second `upgrade`:

    * `CREATE FUNCTION`, not `CREATE OR REPLACE FUNCTION`. With `OR REPLACE`, a
      `downgrade()` missing its `DROP FUNCTION` leaves the old body in place and
      the next `upgrade` silently overwrites it;
    * `NA_REASON.create(..., checkfirst=False)`, not `checkfirst=True`. With
      `True`, a `downgrade()` missing its `DROP TYPE` leaves the old type and the
      next `upgrade` silently reuses whatever labels it happens to have.

    NEITHER CAN BE PROVED BEHAVIOURALLY FROM HERE, and pretending otherwise is
    the trap. Both fire only when `downgrade()` is already broken, and the round
    trip this suite runs always downgrades CLEANLY first — so the guarded path is
    never entered and the guard is never exercised. MEASURED 2026-08-05:
    `CREATE FUNCTION` -> `CREATE OR REPLACE FUNCTION` and `checkfirst=False` ->
    `checkfirst=True` each left the suite at `159 passed`.

    A behavioural test would have to break `downgrade()` on purpose, run two
    upgrades, and put the file back — which is a second, unreviewed copy of
    `0001` living inside a test, for a property that reading one line settles.
    So this reads the line. What it can prove: the strict spelling is present.
    What it CANNOT prove: that the strict spelling does what the comment beside
    it says. That claim rests on PostgreSQL's documented behaviour for
    `CREATE FUNCTION` on an existing name (`42723 duplicate_function`) and on
    SQLAlchemy's for `checkfirst`, and on nothing in this repository.

    No database, so no fixture and no container.
    """
    source = MIGRATION_SOURCE.read_text(encoding="utf-8")

    assert "CREATE OR REPLACE FUNCTION" not in source, (
        "0001 uses CREATE OR REPLACE FUNCTION. A downgrade that forgets its "
        "DROP FUNCTION would then be silently overwritten by the next upgrade "
        "instead of failing as a duplicate."
    )
    assert "CREATE FUNCTION " in source, (
        "0001 no longer contains a plain `CREATE FUNCTION `, so the guard above "
        "is asserting the absence of something that is not there either way"
    )
    assert "checkfirst=True" not in source, (
        "0001 creates or drops the enum with checkfirst=True. A type that already "
        "exists at upgrade time means a previous downgrade failed to drop it, and "
        "that must be an error rather than a silent reuse of its old labels."
    )
    # `checkfirst=False)` with the closing parenthesis, so the prose in `0001`'s
    # own comments — which names the argument in backticks — is not counted as a
    # call site.
    calls = source.count("checkfirst=False)")
    assert calls == 2, (
        f"expected exactly two `checkfirst=False)` call sites — the enum's CREATE "
        f"in upgrade() and its DROP in downgrade() — found {calls}"
    )


def test_alembic_check_reports_no_difference(
    migrated_database: str, alembic_config: Callable[[str], Config], migration_dsn: str
) -> None:
    """`models.py` and the migrated database agree.

    `command.check` raises `AutogenerateDiffsDetected` when they do not. It is
    genuinely wired — it runs `migrations/env.py`, opens a real connection and
    reflects the real catalog — and the test below is what proves that claim
    rather than asserting it.

    `migrated_database` is requested for ordering, not for its value: `check`
    compares against whatever is in the database, and against an unmigrated one
    it would report seven tables to add and fail for the wrong reason.
    """
    command.check(alembic_config(migration_dsn))


def test_alembic_check_would_notice_a_model_the_database_does_not_have(
    migrated_database: str, alembic_config: Callable[[str], Config], migration_dsn: str
) -> None:
    """The anti-vacuity guard for the test above.

    A `check` that silently did nothing — a broken `target_metadata`, an `env.py`
    that returned before configuring, an exception class that is never raised —
    would leave the test above green forever. So a table is added to
    `Base.metadata` that the database does not have, and `check` must say so.

    `Base.metadata` is process-global, so the table is removed in a `finally`.
    Without that, every later test in this session would see a diff.
    """
    probe = sa.Table(
        "alembic_check_probe", Base.metadata, sa.Column("id", sa.Integer, primary_key=True)
    )
    try:
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(alembic_config(migration_dsn))
    finally:
        Base.metadata.remove(probe)

    # And back to agreeing, proved rather than assumed: the removal above is what
    # every later test in this session depends on.
    command.check(alembic_config(migration_dsn))


# --- `env.py`'s own behaviour ------------------------------------------------
#
# Everything above drives `env.py` down its happy path. What follows covers the
# two paths that END in a `raise`, and the three DSN sources it declares.
#
# The offline refusal is the ONE PLACE IN TASK 3 WHERE A SECURITY PROPERTY RESTS
# ON A `raise` RATHER THAN ON THE DATABASE. Everywhere else the `INHERIT FALSE`
# membership does the enforcing: forget `SET ROLE` and PostgreSQL refuses. In
# `--sql` mode there is no connection to refuse anything, so Alembic would
# cheerfully emit seven `CREATE TABLE`s that a DBA executes as themselves,
# producing exactly the LOGIN-role ownership `roles.sql` exists to make
# impossible. That refusal once had nothing testing it — a historical measurement
# recorded here said replacing `run_migrations_offline`'s body with an ordinary
# implementation left the suite at 124 passed. RE-MEASURED 2026-08-05 on this
# branch, same injection (`context.configure(url=..., literal_binds=True)` plus
# `run_migrations`): `test_offline_sql_mode_is_refused` FAILS. The gap is closed;
# the sentence stays because a comment claiming a test exists is worth less than
# one recording that the claim was checked.


def test_a_programmatic_migration_leaves_the_root_loggers_handlers_attached(
    migrated_database: str, alembic_config: Callable[[str], Config], migration_dsn: str
) -> None:
    """🔴 `fileConfig` MUST NOT RUN WHEN ALEMBIC IS NOT THE ENTRY POINT.

    `logging.config.fileConfig` calls `_clearExistingHandlers()` and then
    `_install_loggers`, which removes and CLOSES every handler on the root logger
    before installing the ini's own. `disable_existing_loggers=False` does not
    protect against this: that flag governs logger OBJECTS, and the handler
    teardown is unconditional. MEASURED 2026-08-05 on this file's `env.py` before
    the gate:

        before: root handlers [<StreamHandler <stderr>>]
        after : root handlers [<StreamHandler <stderr>>]
        our handler still attached: False

    — the count is unchanged because `fileConfig` installs a `StreamHandler` of
    its own, which is exactly why counting handlers proves nothing and IDENTITY
    is what this test asserts. It fired 16 times per suite run, once per
    `command.*` call in this file, because `_alembic_config` does
    `Config(str(ALEMBIC_INI))` and `config_file_name` is therefore always set.

    An application that runs `upgrade head` at startup, a management command, or
    a test would have had its logging configuration silently replaced by
    `alembic.ini`'s.

    `env.py` now gates the call on `config.cmd_opts is not None`. Alembic sets
    `cmd_opts` in exactly one place — `CommandLine.main`, from
    `parser.parse_args` — so it is `None` for every `alembic.command.*` call and
    a `Namespace` when the `alembic` console script is the entry point, which is
    the only situation where owning the process's logging is correct.

    The test below is what stops that gate being written as
    `if False:` and forgotten: the sibling test drives the other branch and
    proves `fileConfig` still runs there.
    """
    root = logging.getLogger()
    marker = logging.NullHandler()
    probe = logging.getLogger("titlepipe_core_probe.programmatic")
    root.addHandler(marker)
    try:
        command.check(alembic_config(migration_dsn))

        assert marker in root.handlers, (
            "a programmatic alembic command tore down the root logger's handlers, "
            "so fileConfig ran when alembic was not the entry point"
        )
        assert probe.disabled is False, "a programmatic alembic command disabled an existing logger"
    finally:
        root.removeHandler(marker)


def test_fileconfig_still_runs_for_the_alembic_cli_and_keeps_existing_loggers_enabled(
    migrated_database: str, alembic_config: Callable[[str], Config], migration_dsn: str
) -> None:
    """The other branch of the gate, and the only cover `disable_existing_loggers` has.

    TWO CLAIMS, and neither is implied by the other.

    **`fileConfig` DOES still run when `cmd_opts` is set.** Otherwise the gate in
    `env.py` could be `if False:` and the sibling test above would still pass —
    `alembic upgrade head` from a shell would silently stop honouring the
    `[loggers]` sections in `alembic.ini`. Proved by the one observable effect
    `fileConfig` has that nothing else here does: the root logger's existing
    handlers are gone afterwards.

    **`disable_existing_loggers=False` is the argument that keeps other people's
    loggers alive**, and it too was untested — MEASURED 2026-08-05: restoring the
    stdlib default of `True` left the suite at `159 passed`. The default disables,
    permanently and process-wide, every logger that already exists and is not
    named in the ini. MEASURED in a process that had imported `asyncio`,
    `urllib3`, `psycopg`, `sqlalchemy`, `fastapi`, `alembic` and
    `titlepipe_core.app`, then called `fileConfig("alembic.ini")` at the default:
    16 loggers newly `disabled=True`, `asyncio`, `psycopg`, `sqlalchemy`,
    `urllib3` and `fastapi` among them. The count is a function of what has been
    imported, which is the point — it grows with the process. The probe below is
    created before the command and is named in no section of `alembic.ini`, so
    it is disabled by the default and untouched by the argument `env.py`
    actually passes.

    `cmd_opts` is set to a real `argparse.Namespace`, which is what the CLI
    passes. `x=None` is supplied because `EnvironmentContext.get_x_argument`
    reads `cmd_opts.x` — nothing in this `env.py` calls it, and a Namespace that
    would `AttributeError` if it ever did is not the thing to leave behind.

    Root's handlers are restored in a `finally`. `fileConfig` closes what it
    removes, so without this the rest of the session logs into whatever
    `alembic.ini` installed.
    """
    root = logging.getLogger()
    saved_handlers = root.handlers[:]
    saved_level = root.level
    marker = logging.NullHandler()
    probe = logging.getLogger("titlepipe_core_probe.cli")
    probe.disabled = False
    root.addHandler(marker)

    config = alembic_config(migration_dsn)
    config.cmd_opts = argparse.Namespace(x=None)
    try:
        command.check(config)

        assert marker not in root.handlers, (
            "fileConfig did NOT run even though cmd_opts was set, so `alembic "
            "upgrade` from a shell no longer honours alembic.ini's [loggers] "
            "sections and the sibling test proves nothing"
        )
        assert probe.disabled is False, (
            "fileConfig disabled a pre-existing logger, so disable_existing_loggers "
            "is not False. The stdlib default switches off every logger not named "
            "in alembic.ini — permanently, process-wide, with no undo."
        )
    finally:
        root.handlers[:] = saved_handlers
        root.setLevel(saved_level)


def test_offline_sql_mode_is_refused(alembic_config: Callable[[str], Config]) -> None:
    """`--sql` must refuse, because it cannot `SET ROLE`.

    The refusal names the role, so the operator is told what the generated script
    would have got wrong rather than merely that this is unsupported.

    NO DATABASE IS TOUCHED, and this test now says so with its argument list
    rather than only in a sentence. It used to request `migration_dsn`, which is
    the fixture chain that STARTS THE CONTAINER, and then never opened a
    connection — the refusal happens before any engine is built.
    `PLACEHOLDER_DSN` is enough, exactly as it is for
    `test_the_first_revision_id_is_the_literal_0001`.
    """
    with pytest.raises(RuntimeError) as raised:
        command.upgrade(alembic_config(PLACEHOLDER_DSN), "head", sql=True)

    message = str(raised.value)
    assert "offline" in message
    assert "titlepipe_owner" in message


def test_a_config_naming_no_database_anywhere_is_refused(
    alembic_config: Callable[[str], Config],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """All three sources empty is a configuration error, and says so.

    Alembic's own behaviour for a missing URL is to build an engine from the
    empty string, which fails somewhere inside SQLAlchemy with a message about a
    driver. The refusal names all three places a DSN can come from, because the
    person reading it is the person who has to supply one.

    NO DATABASE IS TOUCHED. This used to request `migration_dsn` — the fixture
    chain that starts the container — and then immediately `del` the attribute
    that carried it, so the container was started to have its DSN deleted.
    """
    monkeypatch.delenv(DATABASE_URL_VARIABLE, raising=False)
    config = alembic_config(PLACEHOLDER_DSN)
    del config.attributes[ALEMBIC_DSN_ATTRIBUTE]

    with pytest.raises(RuntimeError) as raised:
        command.upgrade(config, "head")

    message = str(raised.value)
    assert DATABASE_URL_VARIABLE in message
    assert "alembic.ini" in message
    assert ALEMBIC_DSN_ATTRIBUTE in message


def test_an_unreachable_dsn_really_does_fail(
    alembic_config: Callable[[str], Config], monkeypatch: pytest.MonkeyPatch
) -> None:
    """The control for the three precedence tests below.

    Each of those points the LOSING sources at `UNREACHABLE_DSN` and asserts the
    command succeeds. That proves nothing unless the unreachable DSN genuinely
    fails — a typo making it reachable, or an `env.py` that silently fell back to
    something else, would make all three pass while checking no precedence at
    all.

    🔴 THE MESSAGE MUST NAME THIS SERVER, NOT MERELY BE AN `OperationalError`.
    `pytest.raises(OperationalError)` alone says nothing about WHICH server was
    unreachable, and this test is the control for three others — an `env.py` that
    ignored every source and built an engine from some third DSN would fail with
    an `OperationalError` too, and this control would call that proof. libpq puts
    the host and port it actually tried into its own message
    (`connection to server at "127.0.0.1", port 1 failed: …`), so the assertion
    can read them back out. Host and port come from the constants the DSN itself
    is built from, so the two cannot drift apart.
    """
    monkeypatch.setenv(DATABASE_URL_VARIABLE, UNREACHABLE_DSN)
    config = alembic_config(UNREACHABLE_DSN)

    with pytest.raises(OperationalError) as raised:
        command.check(config)

    message = str(raised.value)
    assert UNREACHABLE_HOST in message, (
        f"the failure does not name {UNREACHABLE_HOST}, so it is not evidence that "
        f"THIS DSN is the one that failed: {message}"
    )
    assert f"port {UNREACHABLE_PORT}" in message, (
        f"the failure does not name port {UNREACHABLE_PORT}: {message}"
    )


def test_the_caller_attribute_beats_the_environment(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`config.attributes["dsn"]` wins over `TITLEPIPE_DATABASE_URL`.

    This is the precedence the test suite itself depends on: a developer with
    `TITLEPIPE_DATABASE_URL` exported for their own cluster must not have the
    harness quietly migrate it. `command.check` is the probe because it connects
    and reflects without changing anything.
    """
    monkeypatch.setenv(DATABASE_URL_VARIABLE, UNREACHABLE_DSN)

    command.check(alembic_config(migration_dsn))


def test_the_environment_beats_the_ini_file(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`TITLEPIPE_DATABASE_URL` wins over `sqlalchemy.url` in `alembic.ini`.

    This is the deployment path: the committed `alembic.ini` carries no
    credential, and an operator supplies one through the environment. A local
    `sqlalchemy.url` someone left in their working copy must not override it.
    """
    monkeypatch.setenv(DATABASE_URL_VARIABLE, migration_dsn)
    config = alembic_config(migration_dsn)
    del config.attributes[ALEMBIC_DSN_ATTRIBUTE]
    config.set_main_option("sqlalchemy.url", UNREACHABLE_DSN)

    command.check(config)


def test_the_ini_file_is_used_when_nothing_else_names_a_database(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The third source works at all.

    `alembic.ini` ships with no `sqlalchemy.url` — a DSN there would be
    `titlepipe_migration`'s credential in version control — so this is the slot an
    operator may fill locally, and it is declared, so it is tested.

    `set_main_option` goes through `ConfigParser`, where a `%` in a password
    begins an interpolation and raises. The generated migration password is
    `token_urlsafe` and has none, which is exactly why `config.attributes` (a
    plain dict) is the mechanism the harness itself uses.
    """
    monkeypatch.delenv(DATABASE_URL_VARIABLE, raising=False)
    config = alembic_config(migration_dsn)
    del config.attributes[ALEMBIC_DSN_ATTRIBUTE]
    config.set_main_option("sqlalchemy.url", migration_dsn)

    command.check(config)


def test_a_failed_upgrade_leaves_no_partial_schema_behind(
    migrated_database: str,
    alembic_config: Callable[[str], Config],
    migration_dsn: str,
    alembic_version_table: str,
    seam_engine: Callable[[str], Engine],
    tmp_path: Path,
) -> None:
    """🔴 THE WHOLE UPGRADE IS ONE TRANSACTION, ASSERTED RATHER THAN COMMENTED.

    `alembic.ini` used to merely claim `transaction_per_migration` was left at
    its default. A claim in a comment is not a control, and this is the property
    it was claiming: a chain of revisions applied by one `upgrade` either all
    land or none do.

    Proved with a probe revision on top of the real head that creates a table and
    then executes nonsense. If the chain were per-migration, `0001`'s seven tables
    would survive the failure and the assertion below would find them. Because it
    is one transaction, `public` comes back with nothing but Alembic's own version
    table.

    🔴 THE PROBE'S REVISION ID IS `partial_upgrade_probe`, NOT A NUMBER, AND IT
    USED TO BE `"0002"`. Task 4 landed a real `0002`, and two revisions sharing an
    id give `alembic.util.exc.CommandError: Multiple head revisions are present
    for given argument 'head'` plus a `UserWarning: Revision 0002 is present more
    than once` — this test failing on a collision rather than on the property it
    is about. A name that cannot be produced by the `NNNN` convention this
    repository uses for real revisions cannot collide with a future one either.
    `down_revision` follows the real head for the same reason: a probe hanging off
    `0001` would fork the chain instead of extending it.

    🔴 WHAT THIS TEST DOES **NOT** DO, stated because the docstring used to claim
    it did. It said this "demonstrates the case `migrated_database`'s teardown was
    restructured for: an upgrade that fails part way now still gets a teardown,
    because the `command.upgrade` call lives inside the fixture's `try`." IT DOES
    NOT. The upgrade that fails here is the one THIS TEST drives, from inside a
    test body, long after `migrated_database` has finished a successful setup; the
    `finally` below puts the schema back before the fixture's teardown is ever
    reached. Moving `command.upgrade` out of that fixture's `try` changes nothing
    about this test, and `tests/conftest.py::_teardown_migrated_database` records
    the same gap from its own side (its "mutation 2"). Forcing it needs a failing
    revision injected into a module-scoped fixture's SETUP, which cannot be
    reached from a test in the module that fixture serves — the fixture has
    already run by then, and a module-scoped fixture cannot take the
    function-scoped `monkeypatch`. It stays uncovered, and saying so is better
    than a docstring that implies otherwise.

    The probe revision is written to a `tmp_path` and reached through
    `version_locations`, so nothing is ever created in `migrations/versions/` and
    a crash here cannot leave a stray revision behind for the next run.

    ---------------------------------------------------------------------------
    🔴 THE PROBE'S OWN SQLSTATE IS ASSERTED, NOT MERELY `DBAPIError`.
    ---------------------------------------------------------------------------
    This file already sets that standard for the append-only trigger
    (`APPEND_ONLY_SQLSTATE`) and this test did not meet it. If `0001` ITSELF
    broke, `command.upgrade` would still raise a `DBAPIError`, nothing would ever
    be created, and the surviving-relations assertion below would pass
    VACUOUSLY — reporting the transaction-scope property proved while proving
    nothing about it. `42883 undefined_function` is what
    `SELECT this_function_does_not_exist()` raises and is the only failure that
    means the probe got as far as its second statement, i.e. that
    `CREATE TABLE partial_upgrade_probe` really did run and really was rolled
    back.
    """
    (tmp_path / "partial_upgrade_probe.py").write_text(_FAILING_REVISION, encoding="utf-8")

    real_config = alembic_config(migration_dsn)
    versions = Path(str(real_config.get_main_option("script_location"))) / "versions"

    probe_config = alembic_config(migration_dsn)
    # `path_separator`, not the older `version_path_separator` — alembic 1.18.5
    # emits a `DeprecationWarning` for the latter, and this suite runs with
    # `-W` defaults where a warning is noise that trains people to ignore
    # warnings.
    probe_config.set_main_option("path_separator", "os")
    probe_config.set_main_option("version_locations", f"{versions}{os.pathsep}{tmp_path}")

    command.downgrade(real_config, "base")
    try:
        with pytest.raises(DBAPIError) as raised:
            command.upgrade(probe_config, "head")

        assert _sqlstate(raised.value) == UNDEFINED_FUNCTION_SQLSTATE, (
            f"expected SQLSTATE {UNDEFINED_FUNCTION_SQLSTATE} from the probe revision's "
            f"own `SELECT this_function_does_not_exist()`, got "
            f"{_sqlstate(raised.value)}. Anything else means the upgrade failed "
            f"BEFORE the probe ran, and the surviving-relations assertion below would "
            f"then hold vacuously: {raised.value}"
        )

        engine = seam_engine(migrated_database)
        try:
            with engine.connect() as connection:
                surviving = _public_schema_objects(connection, alembic_version_table)
        finally:
            engine.dispose()

        assert surviving["relations"] <= {f"r:{alembic_version_table}"}, (
            "a failed upgrade left objects behind, so the revisions are NOT "
            f"running in one transaction: {sorted(surviving['relations'])}"
        )
        assert surviving["functions"] == set()
        assert surviving["enum_types"] == set()
    finally:
        # Back to head for the rest of the module, and for the fixture's own
        # teardown, which downgrades from wherever this left things.
        command.upgrade(real_config, "head")


# A revision that creates something and then fails, used only by the test above.
# It lives as a string rather than a file in `migrations/versions/` because a
# real file there would be picked up by every ordinary `upgrade` in the suite.
_FAILING_REVISION = '''"""A revision that fails after creating a table. Test fixture only."""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "partial_upgrade_probe"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE TABLE partial_upgrade_probe (id integer)")
    op.execute("SELECT this_function_does_not_exist()")


def downgrade() -> None:
    op.execute("DROP TABLE partial_upgrade_probe")
'''
